export type Lang = "en" | "ru" | "ka";
export type Text = Record<Lang, string>;
export type MenuItem = { id: number; name: Text; desc: Text; price: string; photo: string };
export type MenuCategory = { title: Text; items: MenuItem[] };

export const menu: MenuCategory[] = [
  { title: { en: "Salads", ru: "Салаты", ka: "სალათები" }, items: [
    { id: 0, name: { en: "Gurman salad", ru: "Салат «Гурман»", ka: "სალათი „გურმანი“" }, desc: { en: "Chicken fillet, crackers, lettuce, cucumber, tomato, honey-mustard sauce", ru: "Куриное филе, сухарики, листья салата, огурец, помидор, медово-горчичный соус", ka: "ქათმის ფილე, სუხარი, სალათის ფოთოლი, კიტრი, პომიდორი, თაფლ-მდოგვის სოუსი" }, price: "22", photo: "/images/menu/00.webp" },
    { id: 1, name: { en: "Georgian salad", ru: "Салат «Грузинский»", ka: "სალათი „ქართული“" }, desc: { en: "Cucumber, tomato, pepper, onion, walnut sauce", ru: "Огурец, помидор, болгарский перец, лук, ореховый соус", ka: "კიტრი, პომიდორი, წიწაკა, ხახვი, ნიგვზის სოუსი" }, price: "18", photo: "/images/menu/01.webp" },
    { id: 2, name: { en: "Summer salad", ru: "Салат «Летний»", ka: "სალათი „საზაფხულო“" }, desc: { en: "Lettuce, cucumber, tomato, pepper, cauliflower, onion, sauce", ru: "Листья салата, огурец, помидор, болгарский перец, цветная капуста, лук", ka: "სალათის ფოთოლი, კიტრი, პომიდორი, წიწაკა, ყვავილოვანი კომბოსტო, ხახვი" }, price: "20", photo: "/images/menu/02.webp" },
    { id: 3, name: { en: "Greek salad", ru: "Салат «Греческий»", ka: "სალათი „ბერძნული“" }, desc: { en: "Tomato, cucumber, feta, olives, pepper, onion, lettuce", ru: "Помидор, огурец, фета, оливки, болгарский перец, лук, листья салата", ka: "პომიდორი, კიტრი, ფეტა, ზეთისხილი, წიწაკა, ხახვი" }, price: "19", photo: "/images/menu/03.webp" },
    { id: 4, name: { en: "Caesar", ru: "Цезарь", ka: "სალათი „ცეზარი“" }, desc: { en: "Chicken fillet, lettuce, tomato, crackers, parmesan, Caesar sauce", ru: "Листья салата, помидор, куриное филе, сухарики, пармезан, соус Цезарь", ka: "ქათმის ფილე, სალათის ფოთოლი, პომიდორი, სუხარი, პარმეზანი" }, price: "30", photo: "/images/menu/04.webp" },
    { id: 5, name: { en: "Caesar with shrimps", ru: "Цезарь с креветками", ka: "სალათი „ცეზარი“ კრევეტებით" }, desc: { en: "Shrimps, lettuce, tomato, crackers, parmesan, Caesar sauce", ru: "Листья салата, помидор, креветки, сухарики, пармезан, соус Цезарь", ka: "კრევეტები, სალათის ფოთოლი, პომიდორი, სუხარი, პარმეზანი" }, price: "35", photo: "/images/menu/05.webp" },
    { id: 6, name: { en: "Arugula salad", ru: "Салат «Аругула»", ka: "სალათი „არუგულა“" }, desc: { en: "Arugula, lettuce, champignons, cherry tomatoes, walnut sauce", ru: "Руккола, листья салата, шампиньоны, черри, ореховый соус", ka: "რუკოლა, სალათის ფოთოლი, სოკო, ჩერი, ნიგვზის სოუსი" }, price: "25", photo: "/images/menu/06.webp" },
    { id: 7, name: { en: "Affa salad", ru: "Салат «Аффа»", ka: "სალათი „აფფა“" }, desc: { en: "Avocado, bell pepper, radish, cucumber, salad mix", ru: "Авокадо, болгарский перец, редис, огурец, микс салатов", ka: "ავოკადო, ბულგარული წიწაკა, ბოლოკი, კიტრი, სალათის მიქსი" }, price: "27", photo: "/images/menu/07.webp" },
  ] },
  { title: { en: "Cold starters", ru: "Холодные закуски", ka: "ცივი კერძები" }, items: [
    { id: 8, name: { en: "Vegetables Georgian style", ru: "Овощи по-грузински", ka: "ბოსტნეული ქართულად" }, desc: { en: "Eggplant, zucchini, pepper, pkhali, walnut paste", ru: "Баклажан, кабачок, болгарский перец, пхали, ореховая паста", ka: "ბადრიჯანი, ყაბაყი, ბულგარული წიწაკა, ფხალი, ნიგვზის პასტა" }, price: "20", photo: "/images/menu/08.webp" },
    { id: 9, name: { en: "Eggplant walnut rolls", ru: "Баклажаны с орехами", ka: "ბადრიჯანი ნიგვზით" }, desc: { en: "Grilled eggplant rolled with walnut paste", ru: "", ka: "" }, price: "17", photo: "/images/menu/09.webp" },
    { id: 10, name: { en: "Pkhali", ru: "Пхали", ka: "ფხალი" }, desc: { en: "Pkhali, onion, cilantro, walnut", ru: "Пхали, лук, кинза, грецкий орех", ka: "" }, price: "15", photo: "/images/menu/10.webp" },
    { id: 11, name: { en: "Marinades", ru: "Маринады и соленья", ka: "მარინადი და მწნილი" }, desc: { en: "Cucumber, tomato, pepper, cabbage, jonjoli garlic", ru: "Огурец, помидор, перец, капуста, джонджоли, чеснок", ka: "" }, price: "18", photo: "/images/menu/11.webp" },
    { id: 12, name: { en: "Seasonal vegetables", ru: "Овощное ассорти", ka: "ბოსტნეულის ასორტი" }, desc: { en: "Tomato, cucumber, pepper, fresh greens", ru: "Помидор, огурец, болгарский перец, зелень", ka: "" }, price: "17", photo: "/images/menu/12.webp" },
    { id: 13, name: { en: "Georgian cheese plate", ru: "Сырная нарезка", ka: "ყველის ასორტი" }, desc: { en: "Imeretian, suluguni and smoked suluguni", ru: "Имеретинский, сулугуни, копчёный сулугуни", ka: "" }, price: "25", photo: "/images/menu/13.webp" },
  ] },
  { title: { en: "Hot starters", ru: "Горячие закуски", ka: "ცხელი კერძები" }, items: [
    { id: 14, name: { en: "Baked eggplant", ru: "Баклажан запечённый", ka: "გამომცხვარი ბადრიჯანი" }, desc: { en: "Tomato, suluguni cheese, walnut sauce", ru: "Помидоры, сыр сулугуни, ореховый соус", ka: "პომიდორი, სულუგუნი, ნიგვზის სოუსი" }, price: "28", photo: "/images/menu/14.webp" },
    { id: 15, name: { en: "Dolma", ru: "Долма", ka: "დოლმა" }, desc: { en: "Beef and pork mince, grape leaves, rice, herbs", ru: "Фарш телятина и свинина, листья винограда, рис, зелень", ka: "ღორისა და ხბოს ფარში, ვაზის ფოთოლი, ბრინჯი" }, price: "20", photo: "/images/menu/15.webp" },
    { id: 16, name: { en: "Mushrooms on ketsi", ru: "Грибы на кеци", ka: "სოკო კეცზე" }, desc: { en: "Champignons with suluguni, baked on a clay pan", ru: "Шампиньоны с сулугуни", ka: "სოკო სულგუნით" }, price: "26", photo: "/images/menu/16.webp" },
    { id: 17, name: { en: "Fried suluguni", ru: "Жареный сулугуни", ka: "შემწვარი სულუგუნი" }, desc: { en: "Cheese", ru: "", ka: "" }, price: "20", photo: "/images/menu/17.webp" },
  ] },
  { title: { en: "Soups", ru: "Супы", ka: "სუპები" }, items: [
    { id: 18, name: { en: "Chikhirtma", ru: "Чихиртма", ka: "ჩიხირთმა" }, desc: { en: "Traditional chicken soup with egg and herbs", ru: "Куриный суп", ka: "" }, price: "18", photo: "/images/menu/18.webp" },
    { id: 19, name: { en: "Khashlama", ru: "Хашлама", ka: "ხაშლამა" }, desc: { en: "Slow-cooked beef soup", ru: "Суп с говядиной", ka: "" }, price: "18", photo: "/images/menu/19.webp" },
    { id: 20, name: { en: "Kharcho", ru: "Харчо", ka: "სუპ-ხარჩო" }, desc: { en: "Spiced beef soup with rice", ru: "", ka: "" }, price: "15", photo: "/images/menu/20.webp" },
    { id: 21, name: { en: "Borsch", ru: "Борщ", ka: "ბორში" }, desc: { en: "", ru: "", ka: "" }, price: "14", photo: "/images/menu/21.webp" },
    { id: 22, name: { en: "Meatball soup", ru: "Суп с фрикадельками", ka: "გუფთის წვნიანი" }, desc: { en: "", ru: "", ka: "" }, price: "10", photo: "/images/menu/22.webp" },
    { id: 23, name: { en: "Mushroom cream soup", ru: "Грибной суп-пюре", ka: "სოკოს კრემ-სუპი" }, desc: { en: "", ru: "", ka: "" }, price: "19", photo: "/images/menu/23.webp" },
  ] },
  { title: { en: "Main courses", ru: "Горячие блюда", ka: "მთავარი კერძები" }, items: [
    { id: 24, name: { en: "Chicken tabaka", ru: "Цыплёнок тапака", ka: "წიწილა ტაფაკა" }, desc: { en: "Georgian style pan-pressed chicken", ru: "", ka: "" }, price: "26", photo: "/images/menu/24.webp" },
    { id: 25, name: { en: "Shkmeruli", ru: "Шкмерули", ka: "შქმერული" }, desc: { en: "Chicken fried in a creamy garlic sauce", ru: "Цыплёнок в сливочно-чесночном соусе", ka: "" }, price: "30", photo: "/images/menu/25.webp" },
    { id: 26, name: { en: "Ojakhuri with chicken", ru: "Оджахури с курицей", ka: "ოჯახური ქათმის ხორცით" }, desc: { en: "Chicken meats, potatoes, onion, bell pepper", ru: "Курица, картофель, лук, болгарский перец", ka: "" }, price: "21", photo: "/images/menu/26.webp" },
    { id: 27, name: { en: "Ojakhuri with pork", ru: "Оджахури со свининой", ka: "ოჯახური ღორის ხორცით" }, desc: { en: "Pork meat, potatoes, onion, bell pepper", ru: "Свинина, картофель, лук, болгарский перец", ka: "" }, price: "24", photo: "/images/menu/27.webp" },
    { id: 28, name: { en: "Satsivi", ru: "Сациви", ka: "საცივი" }, desc: { en: "Chicken in traditional garlic and walnut sauce (bazhe)", ru: "Цыплёнок в ореховом соусе баже", ka: "" }, price: "27", photo: "/images/menu/28.webp" },
    { id: 29, name: { en: "Quail with blueberry sauce", ru: "Перепёлка под черничным соусом", ka: "მწყერი მოცვის სოუსით" }, desc: { en: "Quail, blueberry sauce, potatoes, cherry tomatoes", ru: "Перепёлка, черничный соус, картофель, черри", ka: "" }, price: "26", photo: "/images/menu/29.webp" },
    { id: 30, name: { en: "Ojakhuri with veal", ru: "Оджахури с телятиной", ka: "ოჯახური ხბოს ხორცით" }, desc: { en: "Veal, potatoes, onion, bell pepper, tomato", ru: "Телятина, картофель, лук, болгарский перец, помидор", ka: "" }, price: "27", photo: "/images/menu/30.webp" },
    { id: 31, name: { en: "Ojakhuri with mushrooms", ru: "Оджахури с грибами", ka: "ოჯახური სოკოთი" }, desc: { en: "Champignons, potatoes, onion, bell pepper, tomato", ru: "Шампиньоны, картофель, лук, болгарский перец, помидор", ka: "" }, price: "21", photo: "/images/menu/31.webp" },
    { id: 32, name: { en: "Chakhokhbili", ru: "Чахохбили", ka: "ჩახოხბილი" }, desc: { en: "Chicken fillet, tomato sauce, walnuts", ru: "Куриное филе, томатный соус, орехи", ka: "" }, price: "18", photo: "/images/menu/32.webp" },
    { id: 33, name: { en: "Chashushuli with veal and mushrooms", ru: "Чашушули с телятиной и грибами", ka: "ჩაშუშული ხბოს ხორცით და სოკოთი" }, desc: { en: "Veal, mushrooms, vegetables and fresh tomatoes", ru: "Телятина, грибы, овощи, свежие томаты", ka: "" }, price: "24", photo: "/images/menu/33.webp" },
    { id: 34, name: { en: "Chashushuli", ru: "Чашушули", ka: "ჩაშუშული" }, desc: { en: "Veal, tomato sauce, pepper, onion, Georgian spices, cilantro", ru: "Телятина, томатный соус, перец, лук, грузинские специи", ka: "" }, price: "23", photo: "/images/menu/34.webp" },
    { id: 35, name: { en: "Chashushuli with mushrooms", ru: "Чашушули с грибами", ka: "სოკოს ჩაშუშული" }, desc: { en: "Mushrooms, tomato sauce, pepper, onion, Georgian spices, cilantro", ru: "Шампиньоны, томатный соус, перец, лук, грузинские специи, кинза", ka: "" }, price: "16", photo: "/images/menu/35.webp" },
    { id: 36, name: { en: "Chicken cutlets", ru: "Котлеты куриные", ka: "ქათმის კოტლეტი" }, desc: { en: "Served with mashed potatoes", ru: "С картофельным пюре", ka: "" }, price: "24", photo: "/images/menu/36.webp" },
    { id: 37, name: { en: "Lobio", ru: "Лобио", ka: "ლობიო" }, desc: { en: "Red beans, herbs, garlic and Georgian spices", ru: "Фасоль, лук, зелень, орехи, соления", ka: "" }, price: "18", photo: "/images/menu/37.webp" },
  ] },
  { title: { en: "Grill", ru: "Мангал", ka: "მანგალი" }, items: [
    { id: 46, name: { en: "Grilled salmon steak", ru: "Стейк лосося на гриле", ka: "ორაგულის სტეიკი გრილზე" }, desc: { en: "Asian style vegetable salad: eggplant, zucchini, cucumber, cherry tomatoes, arugula, soft cheese, lemon-sesame dressing", ru: "Салат из овощей по-азиатски: баклажан, цукини, огурец, черри, руккола, мягкий сыр, лимонно-кунжутная заправка", ka: "აზიური სტილის ბოსტნეულის სალათი" }, price: "37", photo: "/images/menu/46.webp" },
    { id: 47, name: { en: "Grilled dorado fillet", ru: "Филе дорадо на гриле", ka: "დორადოს ფილე გრილზე" }, desc: { en: "Asian style vegetable salad: eggplant, zucchini, cucumber, cherry tomatoes, arugula, soft cheese, lemon-sesame dressing", ru: "Салат из овощей по-азиатски: баклажан, цукини, огурец, черри, руккола, мягкий сыр, лимонно-кунжутная заправка", ka: "აზიური სტილის ბოსტნეულის სალათი" }, price: "35", photo: "/images/menu/47.webp" },
    { id: 48, name: { en: "Trout", ru: "Форель", ka: "კალმახი" }, desc: { en: "", ru: "", ka: "" }, price: "18", photo: "/images/menu/48.webp" },
    { id: 49, name: { en: "Trout with tarragon", ru: "Форель с тархуном", ka: "კალმახი ტარხუნით" }, desc: { en: "", ru: "", ka: "" }, price: "21", photo: "/images/menu/49.webp" },
    { id: 50, name: { en: "Pork shashlik", ru: "Шашлык из свинины", ka: "ღორის მწვადი" }, desc: { en: "", ru: "", ka: "" }, price: "27", photo: "/images/menu/50.webp" },
    { id: 51, name: { en: "Veal shashlik", ru: "Шашлык из телятины", ka: "ხბოს მწვადი" }, desc: { en: "", ru: "", ka: "" }, price: "30", photo: "/images/menu/51.webp" },
    { id: 52, name: { en: "Chicken shashlik", ru: "Шашлык из курицы", ka: "ქათმის მწვადი" }, desc: { en: "", ru: "", ka: "" }, price: "23", photo: "/images/menu/52.webp" },
    { id: 53, name: { en: "Chalagadzhi", ru: "Чалагаджи", ka: "ღორის ჩალაღაჯი" }, desc: { en: "Pork steak on the bone", ru: "Свиной стейк на кости", ka: "" }, price: "35", photo: "/images/menu/53.webp" },
    { id: 54, name: { en: "Veal chalagadzhi", ru: "Телячий чалагаджи", ka: "ხბოს ჩალაღაჯი" }, desc: { en: "Veal steak on the bone", ru: "Телячий стейк на кости", ka: "" }, price: "45", photo: "/images/menu/54.webp" },
    { id: 55, name: { en: "Chicken steak", ru: "Стейк куриный", ka: "ქათმის სტეიკი" }, desc: { en: "", ru: "", ka: "" }, price: "25", photo: "/images/menu/55.webp" },
    { id: 56, name: { en: "Georgian kebab", ru: "Кебаб по-грузински", ka: "ქაბაბი ქართულად" }, desc: { en: "Pork and veal mix", ru: "Свинина и телятина", ka: "" }, price: "25", photo: "/images/menu/56.webp" },
    { id: 57, name: { en: "Lamb kebab", ru: "Кебаб из баранины", ka: "ცხვრის ქაბაბი" }, desc: { en: "Served with vegetable salad", ru: "С овощным салатом", ka: "" }, price: "27", photo: "/images/menu/57.webp" },
    { id: 58, name: { en: "Chicken kebab", ru: "Кебаб из курицы", ka: "ქათმის ქაბაბი" }, desc: { en: "", ru: "", ka: "" }, price: "22", photo: "/images/menu/58.webp" },
    { id: 59, name: { en: "Grilled vegetables", ru: "Овощи гриль", ka: "ბოსტნეული გრილზე" }, desc: { en: "Tomato, zucchini, eggplant, Bulgarian pepper, onion, mushrooms", ru: "Помидоры, цукини, баклажаны, перец болгарский, лук, шампиньоны", ka: "" }, price: "24", photo: "/images/menu/59.webp" },
  ] },
  { title: { en: "Khachapuri & bread", ru: "Хачапури и выпечка", ka: "ხაჭაპური და პური" }, items: [
    { id: 60, name: { en: "Imeretian khachapuri", ru: "Хачапури имеретинский", ka: "იმერული ხაჭაპური" }, desc: { en: "Round cheese-filled bread", ru: "Круглый, с сыром внутри", ka: "" }, price: "20", photo: "/images/menu/60.webp" },
    { id: 61, name: { en: "Megrelian khachapuri", ru: "Хачапури мегрельский", ka: "მეგრული ხაჭაპური" }, desc: { en: "Cheese inside and on top", ru: "Сыр внутри и сверху", ka: "" }, price: "24", photo: "/images/menu/61.webp" },
    { id: 62, name: { en: "Adjarian khachapuri", ru: "Хачапури аджарский", ka: "აჭარული ხაჭაპური" }, desc: { en: "Boat-shaped, with egg and butter", ru: "Лодочка с яйцом и маслом", ka: "ნავი კვერცხითა და კარაქით" }, price: "21", photo: "/images/menu/62.webp" },
    { id: 63, name: { en: "Khachapuri on a skewer", ru: "Хачапури на шампуре", ka: "ხაჭაპური შამფურზე" }, desc: { en: "Cheese-filled bread baked on a skewer", ru: "", ka: "" }, price: "29", photo: "/images/menu/63.webp" },
    { id: 64, name: { en: "Lavash", ru: "Лаваш", ka: "ლავაში" }, desc: { en: "", ru: "", ka: "" }, price: "3", photo: "/images/menu/64.webp" },
  ] },
  { title: { en: "Side dishes", ru: "Гарниры", ka: "გარნირი" }, items: [
    { id: 38, name: { en: "Mexican potatoes", ru: "Картофель по-мексикански", ka: "კარტოფილი მექსიკურად" }, desc: { en: "", ru: "", ka: "" }, price: "16", photo: "/images/menu/38.webp" },
    { id: 39, name: { en: "French fries", ru: "Картофель фри", ka: "კარტოფილი ფრი" }, desc: { en: "", ru: "", ka: "" }, price: "10", photo: "/images/menu/39.webp" },
    { id: 40, name: { en: "Home style potatoes", ru: "Картофель по-домашнему", ka: "კარტოფილი ოჯახურად" }, desc: { en: "", ru: "", ka: "" }, price: "12", photo: "/images/menu/40.webp" },
    { id: 41, name: { en: "Mashed potatoes", ru: "Картофельное пюре", ka: "კარტოფილის პიურე" }, desc: { en: "", ru: "", ka: "" }, price: "8", photo: "/images/menu/41.webp" },
    { id: 42, name: { en: "Spinach with cream", ru: "Шпинат со сливками", ka: "ისპანახი ნაღებით" }, desc: { en: "", ru: "", ka: "" }, price: "16", photo: "/images/menu/42.webp" },
    { id: 43, name: { en: "Boiled rice", ru: "Рис отварной", ka: "მოხარშული ბრინჯი" }, desc: { en: "", ru: "", ka: "" }, price: "7", photo: "/images/menu/43.webp" },
    { id: 44, name: { en: "Rice with vegetables", ru: "Рис с овощами", ka: "ბრინჯი ბოსტნეულით" }, desc: { en: "Rice, carrot, onion, bell pepper", ru: "Рис, морковь, лук, перец болгарский", ka: "" }, price: "10", photo: "/images/menu/44.webp" },
    { id: 45, name: { en: "Asian style vegetables", ru: "Овощи по-азиатски", ka: "ბოსტნეული აზიურად" }, desc: { en: "", ru: "", ka: "" }, price: "17", photo: "/images/menu/45.webp" },
  ] },
  { title: { en: "Desserts", ru: "Десерты", ka: "დესერტები" }, items: [
    { id: 72, name: { en: "Fried suluguni with fruit sauce", ru: "Жареный сулугуни с фруктовым соусом", ka: "შემწვარი სულუგუნი ხილის სოუსში" }, desc: { en: "", ru: "", ka: "" }, price: "24", photo: "/images/menu/72.webp" },
    { id: 73, name: { en: "Pancakes", ru: "Блинчики", ka: "ბლინები" }, desc: { en: "Cottage cheese, blueberry sauce", ru: "Творог, черничный соус", ka: "ხაჭო, მოცვის სოუსი" }, price: "17", photo: "/images/menu/73.webp" },
    { id: 74, name: { en: "Vanilla ice cream", ru: "Мороженое ванильное", ka: "ვანილის ნაყინი" }, desc: { en: "", ru: "", ka: "" }, price: "10", photo: "/images/menu/74.webp" },
    { id: 75, name: { en: "Chocolate ice cream", ru: "Мороженое шоколадное", ka: "შოკოლადის ნაყინი" }, desc: { en: "", ru: "", ka: "" }, price: "10", photo: "/images/menu/75.webp" },
    { id: 76, name: { en: "Tiramisu", ru: "Тирамису", ka: "ტირამისუ" }, desc: { en: "", ru: "", ka: "" }, price: "18", photo: "/images/menu/76.webp" },
  ] },
];
