"use client";

import Image from "next/image";
import { AnimatePresence, motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { useEffect, useRef, useState } from "react";

type Lang = "en" | "ru" | "ka";
type Text = Record<Lang, string>;
type Pizza = { id: string; name: Text; ingredients: Text; price: number; image: string; spicy?: boolean; vegetarian?: boolean };
const phone = "+995514888800";
const wolt = "https://wolt.com/en/geo/batumi/restaurant/pizza-room-batumi";
const map = "https://www.google.com/maps/search/?api=1&query=Pizza+Room+Batumi+Mall+Gorgiladze+88";
const t = (en: string, ru: string, ka: string): Text => ({ en, ru, ka });

const pizzas: Pizza[] = [
  {id:"pepperoni",name:t("Pepperoni","Пепперони","პეპერონი"),ingredients:t("Pizza sauce, mozzarella, pepperoni","Пицца-соус, моцарелла, пепперони","პიცის სოუსი, მოცარელა, პეპერონი"),price:25,image:"pepperoni",spicy:true},
  {id:"margherita",name:t("Margherita","Маргарита","მარგარიტა"),ingredients:t("Pizza sauce, double mozzarella, tomato, basil","Пицца-соус, двойная моцарелла, помидоры, базилик","პიცის სოუსი, ორმაგი მოცარელა, პომიდორი, ბაზილიკა"),price:25,image:"margherita",vegetarian:true},
  {id:"hawaiian",name:t("Hawaiian","Гавайская","ჰავაი"),ingredients:t("Pizza sauce, mozzarella, turkey, pineapple","Пицца-соус, моцарелла, ветчина индейки, ананас","პიცის სოუსი, მოცარელა, ინდაურის ლორი, ანანასი"),price:26,image:"hawaiian"},
  {id:"mushroom-ham",name:t("Mushrooms & ham","Грибы и ветчина","სოკო და ლორი"),ingredients:t("Pizza sauce, mozzarella, mushrooms, turkey, pickles","Пицца-соус, моцарелла, шампиньоны, ветчина индейки, огурцы","პიცის სოუსი, მოცარელა, სოკო, ინდაურის ლორი, კიტრი"),price:26,image:"mushroom-ham-v3"},
  {id:"vegetarian",name:t("Vegetarian","Вегетарианская","ვეგეტარიანული"),ingredients:t("Pizza sauce, mozzarella, mushrooms, tomato, feta, olives, basil","Пицца-соус, моцарелла, шампиньоны, помидоры, фета, маслины, базилик","პიცის სოუსი, მოცარელა, სოკო, პომიდორი, ფეტა, ზეთისხილი, ბაზილიკა"),price:26,image:"vegetarian-v3",vegetarian:true},
  {id:"pepperoni-jalapeno",name:t("Pepperoni jalapeño","Пепперони халапеньо","პეპერონი ხალაპენო"),ingredients:t("Pizza sauce, mozzarella, pepperoni, jalapeño","Пицца-соус, моцарелла, пепперони, халапеньо","პიცის სოუსი, მოცარელა, პეპერონი, ხალაპენო"),price:26,image:"pepperoni-jalapeno",spicy:true},
  {id:"chicken-ranch",name:t("Chicken ranch","Цыплёнок ранч","ქათმის რანჩი"),ingredients:t("White sauce, mozzarella, chicken, tomato, red onion, ranch sauce","Белый соус, моцарелла, курица, помидоры, красный лук, соус ранч","თეთრი სოუსი, მოცარელა, ქათამი, პომიდორი, წითელი ხახვი, რანჩის სოუსი"),price:26,image:"chicken-ranch"},
  {id:"bbq",name:t("BBQ","Барбекю","ბარბექიუ"),ingredients:t("Pizza sauce, mozzarella, bacon, tomato, onion, BBQ sauce","Пицца-соус, моцарелла, бекон, помидоры, лук, соус барбекю","პიცის სოუსი, მოცარელა, ბეკონი, პომიდორი, ხახვი, ბარბექიუს სოუსი"),price:27,image:"bbq"},
  {id:"pepperoni-grill",name:t("Pepperoni grill","Пепперони гриль","პეპერონი გრილი"),ingredients:t("Pizza sauce, mozzarella, pepperoni, BBQ sauce","Пицца-соус, моцарелла, пепперони, соус барбекю","პიცის სოუსი, მოცარელა, პეპერონი, ბარბექიუს სოუსი"),price:27,image:"pepperoni-grill",spicy:true},
  {id:"chicken-bbq",name:t("Chicken BBQ","Цыплёнок BBQ","ქათმის ბარბექიუ"),ingredients:t("Pizza sauce, mozzarella, chicken, tomato, onion, BBQ sauce","Пицца-соус, моцарелла, курица, помидоры, лук, соус барбекю","პიცის სოუსი, მოცარელა, ქათამი, პომიდორი, ხახვი, ბარბექიუს სოუსი"),price:27,image:"chicken-bbq"},
  {id:"five-cheese",name:t("Five cheese","Пять сыров","5 ყველი"),ingredients:t("White sauce, mozzarella, parmesan, blue cheese, feta, cheddar, basil","Белый соус, моцарелла, пармезан, дорблю, фета, чеддер, базилик","თეთრი სოუსი, მოცარელა, პარმეზანი, ლურჯი ყველი, ფეტა, ჩედარი, ბაზილიკა"),price:27,image:"five-cheese",vegetarian:true},
  {id:"carbonara",name:t("Carbonara","Карбонара","კარბონარა"),ingredients:t("Cream, mozzarella, mushrooms, bacon, parmesan","Сливки, моцарелла, шампиньоны, бекон, пармезан","ნაღები, მოცარელა, სოკო, ბეკონი, პარმეზანი"),price:29,image:"carbonara"},
  {id:"burger",name:t("Pizza burger","Пицца-бургер","პიცა ბურგერი"),ingredients:t("Pizza sauce, mozzarella, beef, cheddar, tomato, onion, pickles, grill sauce, sesame","Пицца-соус, моцарелла, говядина, чеддер, помидоры, лук, огурцы, соус гриль, кунжут","პიცის სოუსი, მოცარელა, საქონლის ხორცი, ჩედარი, პომიდორი, ხახვი, კიტრი, სეზამი"),price:29,image:"burger"},
  {id:"premium",name:t("Premium","Премиум","პრემიუმი"),ingredients:t("Pizza sauce, mozzarella, salami, turkey, bacon, pepperoni, arugula","Пицца-соус, моцарелла, салями, ветчина индейки, бекон, пепперони, рукола","პიცის სოუსი, მოცარელა, სალიამი, ინდაური, ბეკონი, პეპერონი, რუკოლა"),price:32,image:"premium"},
  {id:"salmon",name:t("With salmon","С лососем","ორაგულით"),ingredients:t("Pizza sauce, mozzarella, salmon, cream cheese, dill","Пицца-соус, моцарелла, лосось, крем-сыр, укроп","პიცის სოუსი, მოცარელა, ორაგული, კრემ-ყველი, კამა"),price:32,image:"salmon"},
];

const copy = {
  en: {menu:"Menu",story:"Our story",visit:"Visit us",order:"Order delivery",eyebrow:"BATUMI · EST. 2018",headline:"GOOD PIZZA.\nGOOD MOOD.",intro:"Your next favorite slice is closer than you think. Freshly made 33 cm pizzas, ready for the table or your doorstep.",explore:"Explore the menu",scroll:"SCROLL TO EXPLORE",menuEyebrow:"THE GOOD STUFF",menuTitle:"Find your slice.",menuIntro:"15 pizzas, baked for every kind of craving. Tap a pizza for its ingredients and a quick way to order.",all:"All pizzas",classic:"Classics",spicy:"Spicy",veggie:"Vegetarian",details:"View pizza",size:"33 cm pizza",ingredients:"Ingredients",call:"Call to order",online:"Order on Wolt",close:"Close details",aboutEyebrow:"THE PIZZA ROOM WAY",aboutTitle:"Made to share.\nHard to share.",aboutText:"From the first bite to the last slice, Pizza Room keeps it simple: pizza for the moments that bring people together.",visitEyebrow:"FIND YOUR WAY",visitTitle:"Come hungry.\nLeave happy.",address:"Batumi Mall, 88 Zurab Gorgiladze St, Batumi",hours:"Every day · 11:00–23:00",directions:"Get directions",phone:"Call us",foot:"A concept redesign for Pizza Room Batumi.",priceNote:"Prices from the restaurant’s website menu; delivery prices may differ. Please confirm before ordering.",popular:"FAN FAVORITES",highlight:"A little round of happiness",highlightText:"Hot from the oven, made for the moment."},
  ru: {menu:"Меню",story:"О нас",visit:"Контакты",order:"Заказать доставку",eyebrow:"БАТУМИ · С 2018 ГОДА",headline:"ПИЦЦА ДЛЯ\nХОРОШЕГО ДНЯ.",intro:"Любимая пицца ближе, чем кажется. Свежая пицца 33 см — для вечера с друзьями или доставки домой.",explore:"Смотреть меню",scroll:"ЛИСТАЙ НИЖЕ",menuEyebrow:"САМОЕ ВКУСНОЕ",menuTitle:"Выбирай свою.",menuIntro:"15 пицц на любой вкус. Нажми на карточку, чтобы увидеть состав и заказать.",all:"Все пиццы",classic:"Классика",spicy:"Острые",veggie:"Без мяса",details:"Подробнее",size:"Пицца 33 см",ingredients:"Состав",call:"Позвонить и заказать",online:"Заказать в Wolt",close:"Закрыть",aboutEyebrow:"АТМОСФЕРА PIZZA ROOM",aboutTitle:"Создана, чтобы\nделиться.",aboutText:"Для встречи с друзьями, обеда или домашнего вечера — Pizza Room делает пиццу для моментов, которые хочется разделить.",visitEyebrow:"ЖДЁМ В ГОСТИ",visitTitle:"Приходи\nголодным.",address:"Batumi Mall, ул. Зураба Горгиладзе, 88, Батуми",hours:"Каждый день · 11:00–23:00",directions:"Построить маршрут",phone:"Позвонить",foot:"Демо-редизайн для Pizza Room Batumi.",priceNote:"Цены взяты из меню на сайте ресторана; при доставке они могут отличаться. Уточните перед заказом.",popular:"ПОПУЛЯРНОЕ",highlight:"Круглая порция счастья",highlightText:"Горячая из печи — как раз к твоему столу."},
  ka: {menu:"მენიუ",story:"ჩვენ შესახებ",visit:"კონტაქტი",order:"შეკვეთა",eyebrow:"ბათუმი · 2018 წლიდან",headline:"კარგი პიცა.\nკარგი განწყობა.",intro:"თქვენი საყვარელი პიცა ახლოსაა. ახლად მომზადებული 33 სმ პიცა — ადგილზე ან მიტანით.",explore:"მენიუს ნახვა",scroll:"ჩამოსქროლეთ",menuEyebrow:"გემრიელი არჩევანი",menuTitle:"აირჩიეთ პიცა.",menuIntro:"15 პიცა ნებისმიერი გემოვნებისთვის. დააჭირეთ ბარათს შემადგენლობისა და შეკვეთის სანახავად.",all:"ყველა პიცა",classic:"კლასიკური",spicy:"ცხარე",veggie:"ხორცის გარეშე",details:"დეტალები",size:"33 სმ პიცა",ingredients:"შემადგენლობა",call:"დარეკვა",online:"შეკვეთა Wolt-ზე",close:"დახურვა",aboutEyebrow:"PIZZA ROOM-ის ატმოსფერო",aboutTitle:"გაზიარებისთვის\nშექმნილი.",aboutText:"მეგობრებთან შეხვედრისთვის, სადილისთვის თუ სახლში საღამოსთვის — Pizza Room ქმნის პიცას საერთო მომენტებისთვის.",visitEyebrow:"გელოდებით",visitTitle:"მოდით\nმშიერი.",address:"ბათუმი მოლი, ზურაბ გორგილაძის ქ. 88, ბათუმი",hours:"ყოველდღე · 11:00–23:00",directions:"მარშრუტის ნახვა",phone:"დარეკვა",foot:"Pizza Room Batumi-ს კონცეპტუალური რედიზაინი.",priceNote:"ფასები აღებულია რესტორნის ვებსაიტის მენიუდან; მიტანის ფასები შეიძლება განსხვავდებოდეს. შეკვეთამდე გადაამოწმეთ.",popular:"პოპულარული",highlight:"მრგვალი ბედნიერება",highlightText:"ცხელი ღუმელიდან — თქვენს მაგიდამდე."},
};

export default function Home() {
  const [lang,setLang]=useState<Lang>("en");
  const [filter,setFilter]=useState("all");
  const [selected,setSelected]=useState<Pizza|null>(null);
  const [mobileOpen,setMobileOpen]=useState(false);
  const reduce=useReducedMotion();
  const heroRef=useRef<HTMLElement>(null);
  const [smallScreen,setSmallScreen]=useState(false);
  const {scrollYProgress}=useScroll({target:heroRef,offset:["start start","end end"]});
  const pizzaTurn=useTransform(scrollYProgress,[0,1],[0,140]);
  const pizzaGrow=useTransform(scrollYProgress,[0,1],[1,1.35]);
  const pizzaDrift=useTransform(scrollYProgress,[0,1],[0,65]);
  const copyRise=useTransform(scrollYProgress,[0,1],[0,-95]);
  const c=copy[lang];
  const filtered=pizzas.filter(p=>filter==="all" || filter==="spicy"&&p.spicy || filter==="veggie"&&p.vegetarian || filter==="classic"&&["pepperoni","margherita","hawaiian","bbq","carbonara"].includes(p.id));
  useEffect(()=>{document.documentElement.lang=lang},[lang]);
  useEffect(()=>{const sync=()=>setSmallScreen(window.innerWidth<=820);sync();window.addEventListener("resize",sync);return()=>window.removeEventListener("resize",sync)},[]);
  useEffect(()=>{document.body.style.overflow=selected?"hidden":"";return()=>{document.body.style.overflow=""}},[selected]);
  return <>
    <header className="site-header"><div className="header-inner">
      <a className="brand" href="#top" aria-label="Pizza Room home"><span className="brand-mark"><Image src="/images/brand-mark.webp" alt="" fill sizes="52px" /></span><span className="brand-words">PIZZA <b>ROOM</b></span></a>
      <nav className={mobileOpen?"nav open":"nav"} aria-label="Main navigation"><a href="#menu" onClick={()=>setMobileOpen(false)}>{c.menu}</a><a href="#story" onClick={()=>setMobileOpen(false)}>{c.story}</a><a href="#visit" onClick={()=>setMobileOpen(false)}>{c.visit}</a></nav>
      <div className="header-actions"><div className="languages" aria-label="Language">{(["en","ru","ka"] as Lang[]).map(l=><button key={l} className={lang===l?"active":""} onClick={()=>{setLang(l);setMobileOpen(false)}} aria-pressed={lang===l}>{l==="ka"?"GE":l.toUpperCase()}</button>)}</div><a className="header-order" href={wolt} target="_blank" rel="noopener noreferrer">{c.order}<span aria-hidden="true">↗</span></a><button className="mobile-toggle" aria-label="Toggle menu" aria-expanded={mobileOpen} onClick={()=>setMobileOpen(!mobileOpen)}><span/><span/></button></div>
    </div></header>
    <main id="top">
      <section className="hero" ref={heroRef} aria-labelledby="hero-title"><div className="hero-stage"><div className="hero-noise"/><div className="hero-inner"><motion.div className="hero-copy" style={smallScreen||reduce?undefined:{y:copyRise}}><motion.p className="eyebrow" initial={false} animate={{opacity:1,y:0}} transition={{duration:.55}}><span className="eyebrow-line"/>{c.eyebrow}</motion.p><motion.h1 id="hero-title" initial={false} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.1}}>{c.headline.split("\n").map((line,i)=><span key={i}>{line}</span>)}</motion.h1><motion.p className="hero-intro" initial={false} animate={{opacity:1,y:0}} transition={{duration:.65,delay:.25}}>{c.intro}</motion.p><motion.div className="hero-buttons" initial={false} animate={{opacity:1,y:0}} transition={{duration:.65,delay:.36}}><a className="button button-dark" href="#menu">{c.explore}<span>↗</span></a><a className="text-link" href={wolt} target="_blank" rel="noopener noreferrer">{c.order} <span>↗</span></a></motion.div></motion.div><div className="hero-art" aria-label="Fresh pepperoni pizza"><div className="hero-ring hero-ring-one"/><div className="hero-ring hero-ring-two"/><motion.div className="hero-pizza" style={smallScreen||reduce?undefined:{rotate:pizzaTurn,scale:pizzaGrow,x:pizzaDrift}} initial={false} animate={{opacity:1,scale:1,rotate:0}} transition={{duration:1.1,ease:[.18,.8,.22,1]}}><div className="pizza-spin"><Image src="/images/hero-pizza.webp" alt="Freshly baked pepperoni pizza" fill priority sizes="(max-width: 760px) 90vw, 650px"/></div></motion.div><span className="hero-sticker sticker-top">33<br/><small>CM</small></span><span className="hero-sticker sticker-bottom">HOT<br/> & FRESH ✦</span></div></div><div className="hero-bottom"><span>01 / PIZZA ROOM</span><span>{c.scroll} ↓</span></div></div></section>
      <section className="marquee" aria-hidden="true"><div>FRESHLY MADE <span>✳</span> GOOD TIMES <span>✳</span> PIZZA ROOM <span>✳</span> FRESHLY MADE <span>✳</span> GOOD TIMES <span>✳</span> PIZZA ROOM <span>✳</span></div></section>
      <section className="menu-section" id="menu"><div className="container"><div className="section-top"><div><p className="eyebrow eyebrow-dark"><span className="eyebrow-line"/>{c.menuEyebrow}</p><h2>{c.menuTitle}</h2></div><p className="section-lede">{c.menuIntro}</p></div><div className="filter-row" role="group" aria-label="Pizza filters">{[["all",c.all],["classic",c.classic],["spicy",c.spicy],["veggie",c.veggie]].map(([id,label])=><button key={id} className={filter===id?"filter active":"filter"} onClick={()=>setFilter(id)} aria-pressed={filter===id}>{label}</button>)}</div><div className="pizza-grid">{filtered.map((p)=><motion.button className="pizza-card" key={p.id} onClick={()=>setSelected(p)} whileHover={reduce?undefined:{y:-6}} transition={{duration:.2}} aria-label={`${c.details}: ${p.name[lang]}`}><div className="card-image"><Image src={`/images/${p.image}.webp`} alt={p.name[lang]} fill loading="eager" sizes="(max-width: 600px) 100vw, (max-width: 1000px) 50vw, 33vw"/><span className="card-number">{String(pizzas.indexOf(p)+1).padStart(2,"0")}</span></div><div className="card-content"><div className="card-title-row"><h3>{p.name[lang]}</h3><span>{p.price} ₾</span></div><p>{p.ingredients[lang]}</p><div className="card-bottom"><span>Ø 33 CM {p.spicy?"· 🌶":""}</span><span className="card-arrow" aria-hidden="true">↗</span></div></div></motion.button>)}</div><p className="price-note">{c.priceNote}</p></div></section>
      <section className="statement" id="story"><div className="container statement-inner"><div className="statement-text"><p className="eyebrow"><span className="eyebrow-line"/>{c.aboutEyebrow}</p><h2>{c.aboutTitle.split("\n").map((line,i)=><span key={i}>{line}</span>)}</h2><p>{c.aboutText}</p><a className="button button-yellow" href="#menu">{c.explore}<span>↗</span></a></div><div className="statement-visual"><div className="statement-circle"><Image src="/images/hero-pizza.webp" alt="Pepperoni pizza" fill sizes="(max-width: 800px) 80vw, 500px"/></div><div className="statement-stamp">PIZZA ROOM<br/>BATUMI ✦</div></div></div></section>
      <section className="visit" id="visit"><div className="container visit-inner"><div><p className="eyebrow eyebrow-dark"><span className="eyebrow-line"/>{c.visitEyebrow}</p><h2>{c.visitTitle.split("\n").map((line,i)=><span key={i}>{line}</span>)}</h2></div><div className="visit-info"><p className="visit-address">{c.address}</p><p>{c.hours}</p><div className="visit-buttons"><a className="button button-dark" href={map} target="_blank" rel="noopener noreferrer">{c.directions}<span>↗</span></a><a className="button button-outline" href={`tel:${phone}`}>{c.phone}<span>↗</span></a></div></div></div></section>
    </main><footer><div className="container footer-inner"><a className="footer-brand" href="#top">PIZZA <b>ROOM</b><span>✳</span></a><p>{c.foot}</p><a href="https://www.instagram.com/pizzaroom.batumi/" target="_blank" rel="noopener noreferrer">INSTAGRAM ↗</a></div></footer>
    <AnimatePresence>{selected&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={(e)=>{if(e.target===e.currentTarget)setSelected(null)}}><motion.div className="pizza-modal" role="dialog" aria-modal="true" aria-label={selected.name[lang]} initial={{opacity:0,y:30,scale:.96}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20,scale:.97}} transition={{duration:.25}}><button className="modal-close" onClick={()=>setSelected(null)} aria-label={c.close}>×</button><div className="modal-image"><Image src={`/images/${selected.image}.webp`} alt={selected.name[lang]} fill sizes="(max-width: 720px) 100vw, 45vw"/></div><div className="modal-content"><span className="modal-kicker">PIZZA ROOM · {c.size}</span><h2>{selected.name[lang]}</h2><p className="modal-label">{c.ingredients}</p><p className="modal-description">{selected.ingredients[lang]}</p><div className="modal-price">{selected.price} ₾ <small>Ø 33 CM</small></div><div className="modal-actions"><a className="button button-dark" href={wolt} target="_blank" rel="noopener noreferrer">{c.online}<span>↗</span></a><a className="button button-outline" href={`tel:${phone}`}>{c.call}<span>↗</span></a></div><small className="modal-note">{c.priceNote}</small></div></motion.div></motion.div>}</AnimatePresence>
  </>;
}
